[book]
title = "dummy"
authors = ["dummy 2"]
language = "en"

[output.html]
git-repository-url = "https://github.com/SuvabrataChowdhury/mdbook-deployable-template"
mathjax-support = false
smart-punctuation = false
theme = "src/theme"
