name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  md-checks:
    name: Markdown Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      pull-requests: write
      contents: read
      checks: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v7
      - name: Check Spellings
        uses: streetsidesoftware/cspell-action@v9
        with:
          # Target only your Markdown files
          files: "**/*.md"
          # Ensures it reads your custom config file
          config: "cspell.config.yml"
          # Enable spelling suggestions inside the PR logs/annotations
          suggestions: true
          # Only check files added/modified in this specific PR
          incremental_files_only: true
          # Create visible warning annotations on the PR file diff
          inline: warning
          # Force the action to pass or fail based on typos
          strict: true
      - name: Check Markdown Links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: yes
          base-branch: main
  script-tests:
    name: Script Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Test Init Script
        run: scripts/test/bats/bin/bats scripts/test/init-unit-test.bats
      - name: Test Update Script
        run: scripts/test/bats/bin/bats scripts/test/update-unit-test.bats
