name: Create Release

on:
  push:
    branches:
      - main # Triggers when a PR is merged into main

jobs:
  test:
    name: Test existing scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: ./.github/actions/install-mdbook
        with:
          mdbook-version: 0.5.4
      - uses: ./.github/actions/install-yq
        with:
          yq-version: v4.53.3
          yq-platform: linux_amd64
      - name: Unit Test Init Script
        run: scripts/test/bats/bin/bats scripts/test/init-unit-test.bats
      - name: Integration Test Init Script
        run: scripts/test/bats/bin/bats scripts/test/init-integration-test.bats
  release:
    name: Release Project
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: Allows the workflow to create tags and releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetches all history so the action can accurately parse previous commits/tags

      - name: Calculate Next Version
        id: semver
        uses: PaulHatch/git-semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "/^(feat|fix)\\(.+\\)!:/"
          minor_pattern: "/^feat\\(.+\\):/"
          ignore_commits_pattern: "/^chore\\(.+\\):/"
          version_format: "v${major}.${minor}.${patch}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          name: Release ${{ steps.semver.outputs.version }}
          body: |
            Automated release for version ${{ steps.semver.outputs.version }}

            Changes since last release: Includes commit increments.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
